stages:
  - .pre
  - build
  - test

build_website:
  image: node:18-alpine # node installed alpine docker image
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build
  artifacts:
    paths:
      - build/

.linter: # Disable job
  image: node:18-alpine
  stage: .pre
  before_script:
    - yarn install
  script:
    - yarn lint

test_website:
  image: alpine
  stage: test
  dependencies:
    - build_website
  before_script:
    - yarn install
    - apk add curl
      - yarn global add serve
  script:
    - serve -s build & # Run this command in the background
    - sleep 10 # Sleep for 10 seconds
    - curl http://localhost:3000 | grep "Learn GitLab CI"
.unit_test:
  image: node:18-alpine
  stage: .pre
  before_script:
    - yarn install
  script:
    - yarn test
