stages:
  - .pre
  - build
  - test
default:
  interruptible: false
  before_script:
    - yarn install

unit_test_website:  # Collect Test Reports
  image: node:18-alpine
  stage: .pre
  script:
    - $PACKAGE_MANAGER test --ci --reporters=default --reporters=jest-junit
  artifacts:
    reports:
      junit: junit.xml

linter_website: 
  image: node:18-alpine
  stage: .pre
  script:
    - $PACKAGE_MANAGER lint

variables:
  Node_END: test
  PACKAGE_MANAGER: yarn

build_website:
  image: node:18-alpine # node installed alpine docker image
  stage: build
  script:
    - $PACKAGE_MANAGER build
  artifacts:
    paths:
      - build/
      - running-all-jobs

test_website:
  image: node:18-alpine
  stage: test
  dependencies:
    - build_website
  before_script:
    - apk add curl
    - $PACKAGE_MANAGER global add serve
  script:
    - serve -s build & # Run this command in the background
    - sleep 10 # Sleep for 10 seconds
    - curl -s http://localhost:3000 | grep "React App"

