stages:
  - .pre
  - build
  - test
default:
  interruptible: false
  before_script:
    - yarn install

build_website:
  image: node:18-alpine # node installed alpine docker image
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - build/

.linter: # Disabled job
  image: node:18-alpine
  stage: .pre
  script:
    - yarn lint

test_website:
  image: node:18-alpine
  stage: test
  dependencies:
    - build_website
  before_script:
    - apk add curl
    - yarn global add serve
  script:
    - serve -s build & # Run this command in the background
    - sleep 10 # Sleep for 10 seconds
    - curl http://localhost:3000 | grep "React App"

.unit_test: # Disabled job
  image: node:18-alpine
  stage: .pre
  script:
    - yarn test
