stages:
  - build
  - test
build_website:
  image: node:18-alpine  # node installed alpine docker image
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build 
  artifacts:
    paths:
      - build/

test_website:
  image: alpine
  stage: test
  dependencies:
    - build_website
  script:
    - test -f build/index.html   # Checks if the index.html exists in build folder

unit_test:
  image: node:18-alpine
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test 
