stages:
  - .pre
  - build
  - test

build_website:
  image: node:18-alpine # node installed alpine docker image
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build
  artifacts:
    paths:
      - build/

linter:
  image: node:18-alpine
  stage: .pre
  before_script:
    - yarn install
  script:
    - yarn lint

test_website:
  image: alpine
  stage: test
  dependencies:
    - build_website
  script:
    - test -f build/index.html # Checks if the index.html exists in build folder

unit_test:
  image: node:18-alpine
  stage: .pre
  before_script:
    - yarn install
  script:
    - yarn test
