stages:
  - pre
  - build
  - test

# Default settings for all jobs
default:
  interruptible: false
  before_script:
    - yarn install
    - yarn add --dev jest-junit

# Global variables
variables:
  NODE_ENV: test
  PACKAGE_MANAGER: yarn

# Unit tests job
unit_test_website:
  image: node:18-alpine
  stage: pre
  script:
    - $PACKAGE_MANAGER test --ci --watchAll=false --reporters=default --reporters=jest-junit
  artifacts:
    reports:
      junit: reports/junit.xml

# Linter job
linter_website:
  image: node:18-alpine
  stage: pre
  script:
    - $PACKAGE_MANAGER lint

# Build job
build_website:
  image: node:18-alpine
  stage: build
  script:
    - $PACKAGE_MANAGER build
  artifacts:
    paths:
      - build/ # Make sure this folder exists after build

# Test the built website
test_website:
  image: node:18-alpine
  stage: test
  dependencies:
    - build_website
  before_script:
    - apk add --no-cache curl
    - npm install -g serve
  script:
    - serve -s build -l 3000 & # Serve build folder on port 3000
    - sleep 10 # Give server time to start
    - curl -s http://localhost:3000 | grep "React App"
